Update centos-install.sh
Added rubygems (didnt work otherwise).
Since puppet 2.7.20 has an error, trying with latest 2.7:

----

Installing ri documentation for puppet-2.7.20...


RDoc failure in lib/puppet/parser/lexer.rb at or around line 253 column 13

Before reporting this, could you check that the file
you're documenting compiles cleanly--RDoc is not a
full Ruby parser, and gets confused easily if fed
invalid programs.

The internal error was:

ERROR:  While executing gem ... (NoMethodError)
    undefined method `name' for #<RubyToken::TkLPAREN:0x7fcc3581a8b8>